### ISSUE TITLE
KeyError: 'buster-backports'

### ISSUE THREAD

**Issue by probonopd** [TheAssassin/appimagelint#6] opened 2019-06-10 08:23 UTC
```
me@host:~$ /home/me/Downloads/appimagelint-x86_64.AppImage /home/me/Downloads/Mumble-427b148-x86_64.AppImage 
appimagelint.cli[13896] [INFO] Checking AppImage /home/me/Downloads/Mumble-427b148-x86_64.AppImage
appimagelint.cli[13896] [INFO] Running check "GNU libc ABI check"
appimagelint.glibc_abi_check[13896] [INFO] detected required version for runtime: 2.3.3
appimagelint.glibc_abi_check[13896] [INFO] detected required version for payload: 2.17
appimagelint.glibc_abi_check[13896] [WARNING] could not find version for oldstable, trying backports
appimagelint.glibc_abi_check[13896] [INFO] [✔] AppImage can run on Debian oldstable (jessie)
appimagelint.glibc_abi_check[13896] [INFO] [✔] AppImage can run on Debian stable (stretch)
appimagelint.glibc_abi_check[13896] [WARNING] could not find version for testing, trying backports
Traceback (most recent call last):
  File "/tmp/.mount_appimahLFmu9/usr/conda/lib/python3.7/site-packages/appimagelint/checks/gnu_abi_check_base.py", line 103, in _check_debian_compat
    max_supported_version = versions_map[codename]
KeyError: 'buster'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_appimahLFmu9/usr/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/tmp/.mount_appimahLFmu9/usr/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/.mount_appimahLFmu9/usr/conda/lib/python3.7/site-packages/appimagelint/__main__.py", line 4, in <module>
    run()
  File "/tmp/.mount_appimahLFmu9/usr/conda/lib/python3.7/site-packages/appimagelint/cli.py", line 96, in run
    for testres in check.run():
  File "/tmp/.mount_appimahLFmu9/usr/conda/lib/python3.7/site-packages/appimagelint/checks/gnu_abi_check_base.py", line 76, in run
    for result in self._check_debian_compat(required_version):
  File "/tmp/.mount_appimahLFmu9/usr/conda/lib/python3.7/site-packages/appimagelint/checks/gnu_abi_check_base.py", line 106, in _check_debian_compat
    max_supported_version = versions_map["{}-backports".format(codename)]
KeyError: 'buster-backports'
me@host:~$ /home/me/Downloads/appimagelint-x86_64.AppImage /home/me/Downloads/
appimagelint-x86_64.AppImage     micropad-3.18.1-x86_64.AppImage  Mumble-83bca04-x86_64.AppImage   outer_wall2.stl                  screw2.stl                       
Fanny_Pocket.stl                 Mumble-427b148-x86_64.AppImage   Mumble-b5a0b79-x86_64.AppImage   satisfying-twister.scad          Wallet_All_Parts.stl             
inner.stl                        Mumble-5ffa1a4-x86_64.AppImage   outer.stl                        satisfying-twister.stl           Wallet.stl                       
me@host:~$ /home/me/Downloads/appimagelint-x86_64.AppImage /home/me/Downloads/appimagelint-x86_64.AppImage 
appimagelint.cli[14037] [INFO] Checking AppImage /home/me/Downloads/appimagelint-x86_64.AppImage
appimagelint.cli[14037] [INFO] Running check "GNU libc ABI check"
appimagelint.glibc_abi_check[14037] [INFO] detected required version for runtime: 2.3.3
appimagelint.glibc_abi_check[14037] [INFO] detected required version for payload: 2.14
appimagelint.glibc_abi_check[14037] [WARNING] could not find version for oldstable, trying backports
appimagelint.glibc_abi_check[14037] [INFO] [✔] AppImage can run on Debian oldstable (jessie)
appimagelint.glibc_abi_check[14037] [INFO] [✔] AppImage can run on Debian stable (stretch)
appimagelint.glibc_abi_check[14037] [WARNING] could not find version for testing, trying backports
Traceback (most recent call last):
  File "/tmp/.mount_appima1kePO9/usr/conda/lib/python3.7/site-packages/appimagelint/checks/gnu_abi_check_base.py", line 103, in _check_debian_compat
    max_supported_version = versions_map[codename]
KeyError: 'buster'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_appima1kePO9/usr/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/tmp/.mount_appima1kePO9/usr/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/.mount_appima1kePO9/usr/conda/lib/python3.7/site-packages/appimagelint/__main__.py", line 4, in <module>
    run()
  File "/tmp/.mount_appima1kePO9/usr/conda/lib/python3.7/site-packages/appimagelint/cli.py", line 96, in run
    for testres in check.run():
  File "/tmp/.mount_appima1kePO9/usr/conda/lib/python3.7/site-packages/appimagelint/checks/gnu_abi_check_base.py", line 76, in run
    for result in self._check_debian_compat(required_version):
  File "/tmp/.mount_appima1kePO9/usr/conda/lib/python3.7/site-packages/appimagelint/checks/gnu_abi_check_base.py", line 106, in _check_debian_compat
    max_supported_version = versions_map["{}-backports".format(codename)]
KeyError: 'buster-backports'

```

**Comment by TheAssassin** [comment] 2019-06-10 11:55
Duplicate of #4, please don't open new issues but reopen existing ones.

**Closed as completed by TheAssassin** 2019-06-10 11:55 UTC
